### ISSUE TITLE
My first test issue

### ISSUE THREAD

**Issue by medhatdawoud** [medhatdawoud/AMA#1]
I'm now graduated from computer science and I know bla bla bla and my projects are like bla bla bla

what do you advice me to do next??

**Comment by abdeldjalilhachimi** [comment]
Hello there!
I hope you are doing well, 
I would like to ask you about How can I stay motivated when I feel down  with  job refused, and What do you think if you can make a CV review for Us

**Comment by anastely** [comment]
> Hello there!
> I hope you are doing well,
> I would like to ask you about How can I stay motivated when I feel down with job refused, and What do you think if you can make a CV review for Us

@abdeldjalilhachimi open new issue! To help others, this issue for test :D

**Comment by medhatdawoud** [comment]
Closing this issue not to mess with others
