### ISSUE TITLE
How can I know that i am good at javascript ? 

### ISSUE THREAD

**Issue by egenedy97** [medhatdawoud/AMA#10]

**Comment by medhatdawoud** [comment]
HI Eslam,

That's a very open question, I'd say this depends on how you define good, but the simple advice is to practise more in different projects, prove it by doing it.

not sure if I understood your question correctly, but let me know if you want to get more info, try to be precise to the points you think that you are still not so good at.

Best,
Medhat

**Comment by Mina-Mishail** [comment]
@medhatdawoud , if you please let me give a way to @genedy377 question: 

1) You can check some websites facilities, process , graphics , etc... 
2) Then think how can you make this using what you know(understood) of Javascript.

Try for 3 to 5 times & you will succeed or even reach a point of success then check what is missed so you can search or read more about it.

Finally you will be able to put theories into practice & meet you own work\project requirements.

**Comment by medhatdawoud** [comment]
If both our answers are good enough for you please let me know, I'll close this issue now and we can reopen if you have a different opinion
