### ISSUE TITLE
recommendation for books 

### ISSUE THREAD

**Issue by MostafaMagdSalama** [medhatdawoud/AMA#11]
JS ايه احسن الكتب ممكن اتعلم منها و اخليها مرجع ليا في ال  
 (React , Nodejs)و كدالك ال

**Comment by medhatdawoud** [comment]
Hi Mostafa,

Actually I'm not really into books, I'm usually read the documentation more, but what I read before and was good are:

This book by Douglas Crockford (the creator of JSON), and he made as well a lot of talks about the same book before, you can search YouTube
https://www.amazon.de/JavaScript-Good-Parts-Douglas-Crockford/dp/0596517742?tag=hackr03c-21

and this book by Kyle Simpson and the community, is nice and concise
https://www.amazon.de/You-Dont-Know-JS-Beyond/dp/1491904240/?tag=hackr03c-21

hope that helps,
Medhat
