### ISSUE TITLE
Unable to apply my knowledge about JavaScript into real projects

### ISSUE THREAD

**Issue by mohammedyouness** [medhatdawoud/AMA#12]
Hello there, my question will be related to javascript that I know the language and it's concepts very well, but when I start making a simple project with it, I feel I'm stuck and unable to do it.
simply, unable to apply the knowledge into real projects

Any suggestions or solutions, plz?

**Comment by medhatdawoud** [comment]
Hi Mohamed,

I've kind of answer that in #10 , or these 2 questions seems similar, anyway I'd answer that:

you wouldn't know that you are good in something without practicing, my advice is to watch people code and learn from that and apply it, all what you have is kind of craft not experience as I see, it's kind of a person who can use photoshop in all ways but he cannot make on full project, to learn that you need some mentorship, and you need to practise more and more, try different ideas.

what works for me before is mimicking an application that you know very well like twitter for example, try to make your own version of it, you don't have to make everything exactly the same but what I can grantee is that you will learn tons of stuff in the journey, and don't be afraid to ask and search, try it and let me know.

Cheers,
Medhat
