### ISSUE TITLE
Invest my free time

### ISSUE THREAD

**Issue by Momadeen** [medhatdawoud/AMA#13]
#1 In your view, what's best way to invest my free time to learn more, and make every day has a value ?
#2 Read books or videos

**Comment by mgamaldev** [comment]
#1 invest more and more time in open source project, start with any idea like cloning existing framework, package to automate routine tasks , etc.. Also follow some inspiring people on Twitter and invest your free time on it . It worths :)

#2 Both

**Comment by medhatdawoud** [comment]
Hi Mohammed Hassanein,

That's a great question, and thanks @mgamal92 for helping in the answer 👍 

1. In my opinion is everything mgamal92 mentioned specially contributing to open source projects, being a maintainer is a great thing and I have already an opensource project that you are welcome to contribute to ([react-change-highlight](https://github.com/medhatdawoud/react-change-highlight)), also I can add that you can participate in any NGO, watch this [video](https://youtu.be/zEKGANdvxtY) about an NGO that I've started 2011 during my studying, and I gained later a lot of things back.

2. also Both are important but most important as usual I'm saying documentation as there are some people invested a lot of time writing it and they wrote it well, and books and videos are derived from docs anyway, if you are asking me about my own preference after docs is videos 🥇 

Hope that helps,
Medhat
