### ISSUE TITLE
أفضل المصادر لتعلم الجافا سكريبت ثم الرياكت 

### ISSUE THREAD

**Issue by HusienAdel** [medhatdawoud/AMA#14]
سلام عليكم
انا عايز أفضل المصادر سواء كتب او دورات اونلاين لتعلم الجافا سكريبت لأني كويس ف html, css  وبرضه أطار react وغيرهم من التقنيات الجديدة؟ #7

**Comment by Mina-Mishail** [comment]
Check Brad Traversy  video courses on Udemy .
Modern JavaScript  **From TheBeginning**

Good luck

**Comment by medhatdawoud** [comment]
Hi Husien,

Short answer for HTML + CSS + JavaScript is https://developer.mozilla.org/en-US/docs/Learn
and for React is its documentation https://reactjs.org/docs/getting-started.html

after those you can explore more videos and articles and maybe some book as mentioned in #11 

you can also follow some playlists on youtube for some nice authors, I don't know your preference is Arabic or English just let me know so I can help

Cheers,
Medhat

Regards,
Medhat
