### ISSUE TITLE
road map for working abroad (remote, or relocation jobs)

### ISSUE THREAD

**Issue by islamCodehood** [medhatdawoud/AMA#16]
I am 36 years old pharmacist who started learning front-end web development about 2 years ago. I have finished a google scholarship for Udacity's front-end track. After that I started learning Reactjs and made some side projects like this one 👉🏼 https://suggestmeamovie.cf , and others. Contributing to open-source projects, writing small tutorials and increasing my online presence on linkedin. I started applying for jobs in Egypt but most of jobs were either very low paid ones according to the local market, or  they rejected me because of age, and no prior experience (at least that is what I know 🙄).  
I am still investing in myself with no stopping even made a youtube channel to teach people what I learn https://www.youtube.com/c/Codehood , but from time to time I feel disappointed while trying to save time for my studies beside my full time pharmacist job and there is no new steps along my way.

Then I start thinking of applying for hobs outside Egypt. My question: _**is there a chance for a person on my age without CS background formal education, or work experience? And what is the road map (if there is any) for getting accepted for such abroad jobs?**_

Thank you so much for your time, and efforts. 💙💙

**Comment by MoatazAbdAlmageed** [comment]
Amazing @Islam888 you are doing well

**Comment by Lartwel** [comment]
I am graduating this year from a non-tech major insha'Allah and I am willing to work locally or remotely too(just did a few freelance jobs). I have found a lot of developers on twitter or wherever who are with no prior CS background and they're doing well in their jobs. The CS degree matters for the long-term or when you're learning further tech fields too, but you can learn it on your own after awhile (you may check something like OSSU curriculum on github).

My reply may not help, but I just wanted to share it anyway :) and I also wanted to express my appreciation to your hard work. I checked your youtube channel and it seems that you introduce valuable content there. Wish you all the best.

**Comment by medhatdawoud** [comment]
Hi Islam,

I'm so happy that you asked this question which I got a lot in private messages, I've read your message carefully and I think that you are really on track, don't stop learning and teaching people, checked your Youtube channel as well and seems very interesting we might make collaboration later 🙂.

Regarding your question about finding a job abroad in your age, which I don't feel it's too old to do that, I have already a case for a friend who travelled to the Netherland after 38 years old with 2 kids as well also he is not a CS graduate but he was working in Egypt as a full time developer for a respectable time, so it is possible to have a job even later than your age, based on what I understood is that you are self learning but you never work a full time job as a developer (correct me if I'm wrong) if this is the case I would say continue learning but you need first to work for few months as a developer in Egypt which will make you familiar with the overall work environment and load, at least one year of experience would be a minimum for some companies as the cost of moving developer from abroad to Europe for example is a bit costy so they double check if they made the right pick from the beginning, it's not hard to have this experience but at least keep in mind that any developer in the beginning has to give some compromises so most probably it wouldn't be so profitable for the very first job, first try to have this accomplished then we talk again if you want to give you some tips about applying abroad as it's already in my plan as a video to share.

Wish you all the best,
Medhat

**Comment by islamCodehood** [comment]
Thank you so much for your answer. ❤️❤️ I won't stop learning or teaching, and will continue on track. Collaboration with you would be a great addition. Thanks, again.

**Comment by Mina-Mishail** [comment]
That was pretty experienced advice, thanks for your support
