### ISSUE TITLE
Write a unit test in pseudocode to ensure that your code for this function  has the wished functionality.

### ISSUE THREAD

**Issue by AhmedMuhammedElsaid** [medhatdawoud/AMA#17]
the function that checks if a given string with length n is a
substring of a string with length m. The function should return true if it is a
substring or false otherwise.
 
does this consider a unit test in pseudocode?

Input: str1 = "AXY", str2 = "ADXCPY"
Output: True (str1 is a subsequence of str2)

Input: str1 = "AXY", str2 = "YADXCP"
Output: False (str1 is not a subsequence of str2)

Input: str1 = "gksrek", str2 = "geeksforgeeks"
Output: True (str1 is a subsequence of str2)

**Comment by medhatdawoud** [comment]
Hi Ahmed,

If I understand your question, you mean to decide if this is kind of unit testing or not, the answer is YES it is some sort of unit testing since you can give it any assumed input and should expect a specific result based on that, it's kind of a pure function.

Regards,
Medhat
