### ISSUE TITLE
سفر الفرونت ايند لاوروبا

### ISSUE THREAD

**Issue by hossam-shaheen** [medhatdawoud/AMA#19]
السلام عليكم ازي حضرتك وبدايه حابب اشكرك علي المحتوي اللي بتقدمه ، ثانيا حابب اعرف من حضرتك ايه الحد 
    الادني من المعرفه اللي ساعتها اقدر احاول ان اقدم ان اسافر كفرونت ايند لاوروبا انا بنتقل من الانتقال من كوني ويب ديزاينر  الي فرونت ايند فممكن حضرتك تعرفني امتي اقدر افكر ان اقدم علي وظائف من النوع ده وشكرا .

**Comment by medhatdawoud** [comment]
اهلا بيك يا حسام
الموضوع كله بيتوقف على الشركات اللى بتجيب ناس من بره اوروبا .. فيه شركات بتكون ليها حد ادنى وفيه شركات مش بتركز اوي في التيكنيكال وبترك اكتر على الشخص نفسه .. فانت لو قدرت تشتغل في مصر كفرونت اند في حوالي ٣ مشاريع كويسين ومختلفين عن بعض  في اعتقادي هتكون عندك الحد الادنى اللى بيه تقدر تشتغل في اي حتة مش بس اوروبا

بالتوفيق ليك
