### ISSUE TITLE
مشاركه المشاريع 

### ISSUE THREAD

**Issue by hossam-shaheen** [medhatdawoud/AMA#20]
حضرتك في اخر فيديو اقترحت اننا نقدر نشارك في بروجكتس وحضرتك هترسلنا الكومنتس الخاصه بيك فهل ممكن تعرفني ممكن نبدا باي مشروع والاضافات او التعديلات اللي هتتم ع المشروع حضرتك بتعرفها لينا ايه اللي نقدر نشتغل عليه وشكرا

**Comment by medhatdawoud** [comment]
ممكن تلاقي اي مشروع موجود على جيت هاب هنا وتعمله clone وتشتغل عليه على طول ولو عاوز ترشيحات فيه على الاكونت بتاعي مشاريع ممكن تستعملها في انك تتعلم ... بالتوفيق
