### ISSUE TITLE
(L to R) Extension 

### ISSUE THREAD

**Issue by MAlngaawy** [medhatdawoud/AMA#21]
How did you make this extension .. what is the languages and tools you used in it?
I hope you can make a video about this extension 
Thanks : )

**Comment by medhatdawoud** [comment]
I've used pure Javascript code and the chrome APIs nothing fancy, I'm planning to make a video about that soon if you are interested, please stay tuned

**Comment by MAlngaawy** [comment]
very interesting.
I have another asking
can you make a video about how to make an extension for VScode or atom ?!

**Comment by medhatdawoud** [comment]
I've added it as an option in #28 for people to vote on it, and also another option for the vs extensions, I do have some ideas btw, Thanks for the suggestion 👍
