### ISSUE TITLE
How to design a good folder structure for medium or gigantic react application ?

### ISSUE THREAD

**Issue by Mmferry** [medhatdawoud/AMA#22]

**Comment by medhatdawoud** [comment]
Hi Farid,

This question is kind of duplicated in #4, but again it depends on the project and the team members, how is the best way to work and understand the project it will be the best structure for the project, don't care that much about how other ppl are working except if you have a problem with the current setup and searching for a solution, other than that, keep yourself agile to make the folder structure the best that everyone in the team could understand and maintain.

also if you search online for an answer for that board question, you will find tons of best practises what makes none of them in the best practise, just pick one and adjust it based on your needs.

Goodluck, Medhat

**Comment by Mmferry** [comment]
Hi Medhat,

Thank you I really appreciate your response
