### ISSUE TITLE
XML vs JSON

### ISSUE THREAD

**Issue by saidbakr** [medhatdawoud/AMA#25]
إيه اللي خلى كعب ال
JSON
يعلى على
XML
في نقل البيانات، بالرغم من إن اﻷخير أسهل في كتابته والمتصفحات كلها تلقائيا تقدر تعرضه بشكل أجمل وأوضح؟
بصراحة السؤال ده محيرني وموش عارف إجابته.

**Comment by medhatdawoud** [comment]
Hi Said,

Not sure why 🤷‍♂️ but I can guess that XML is not very understandable for client-side directly, you have to parse it to JSON to use it easily with JavaScript, plus I see JSON is way more readable.

Cheers,
Medhat

**Comment by saidbakr** [comment]
> Hi Said,
> 
> Not sure why man_shrugging but I can guess that XML is not very understandable for client-side directly, you have to parse it to JSON to use it easily with JavaScript, plus I see JSON is way more readable.
> 
> Cheers,
> Medhat

I don't see that. Simply, XML is a DOM. Additionally, any structural or syntax error could be discovered easily without programming. i.e the browser will not load it correctly.

I think, partially as you said "you have to parse it" but everything is extension. In other words, if there are handy extensions or components that performs recalling it as DOM easily, it will get its rewarded consideration  in the development.

**Comment by Mohamed-Abuelatta** [comment]
الجيسون من وجهة نظرى كعبه مش عالى ولا حاجة . ببساطة ده نظام وده نظام تانى خالص . يعنى الاتنين مختلفين عن بعض ولا يمكن وضعهم فى سلة واحدة. 


الجيسون زى ما مدحت قال اسهل فى القرائة بيتعمله بارسينج بسهولة ممكن تتراك عليه بشكل اسهل وده استخدامه الطبيعى والمنطقى خصوصا فى الكلام بين التكنولوجى المختلفة. 

اما اكس ام ال فهى قوية جدا وما زالت فى انك تقدر تستخدمها كداتا بيز وده اللى ميعرفهوش ناس كتير جدا. طبعا مقصدش انها تسنخدم لمشروع كامل ولكن اقصد ممكن مثلا تعمل بيها لاندنج بيج او تستورد وتصدر بيانات لصفحة كاملة وبلغات مختلفة دون الحاجة لاستخدام سيكول سيرفر. والسبب فى ذلك ان اكس ام ال فيها 
١- نيم سبيس ٢- فنكشنز ٣- لووب ٤- كونديشن ٥- باراميترز ٦- فاريابلز ++++++   etc

فى كمان ليها نوعية ملفات تقدر تحولها ل xhtml اسمها xslt 

كل ده مش موجود فى جيسون

**Comment by saidbakr** [comment]
@Mohamed-Abuelatta 
بمنظور مجرد كلاهما
portable data
يعني الوظيفة اﻷساسية واحدة للاتنين.

ظني إن تغلب 
JSON
في نقل البيانات عبر الإنترنت يرجع لحاجة واحدة فقط، وهي توفير الحجم فإنشاء تاج وإغلاقه بنفس الإسم يزيد حجم البيانات بمعدل أكبر في
xml
مقارنة ب 
JSON

وجانبيا، فعلا في التطبيقات البسيطة استخدامه كمصدر بيانات يكون مفيد للغاية وسهل، فعندي مثلا فورم اتصال على موقعي احفظ بياناته على إكس إم إل، ولست بحاجة لإنشاء 
view 
له، حيث أقوم بفتحه من خلال المتصفح محليا ﻷعاين المدخلات الجديدة.

**Comment by medhatdawoud** [comment]
That was a good discussion, I'll archive this for later 👍 Thanks
