### ISSUE TITLE
what should I do to deep in javascript?

### ISSUE THREAD

**Issue by AkramAdil** [medhatdawoud/AMA#26]
I learned Javascript basics, some advanced topics, dom, bom, json and ajax. I want to know more about javascript should I make more projects or learn node.js and then make projects?

**Comment by medhatdawoud** [comment]
Hi Akram,

I'm sorry for the very late response, regarding your question, You don't have to learn Nodejs to make projects, you can start making some POCs using the frontend only or using some open APIs like https://apilist.fun and start making the frontend yourself, as I mentioned in this video https://www.youtube.com/watch?v=ymefJgsOuNs& , there are some ideas I hope it helps you.

Goodluck,
Medhat
