### ISSUE TITLE
Suggestion: JavaScript course from beginners to intermediate with new concept.

### ISSUE THREAD

**Issue by saidbakr** [medhatdawoud/AMA#27]
I suggest to plan new JavaScript course, tutorial, etc but using new concept of learning for beginners. The majority of tutorials for beginners starts as a **Crude Simple** i.e. using only a text editor, `console.log`, `alert()`, etc. The student may lose the excitement of learning or he/she consumes relatively long time without familiarity of new topics.

The new concept I suggest is  **Encapsulated Crude Simple**. In this approach, you, as instructor, will start the tutorial using a **Starter Kit**.

Suppose that you will start a JavaScript tutorial for beginners using **ECS** concept described above, you may follow the following instructions:
 1. Ordered copy & paste commands that allows cloning and running your project named [VueJS Playground](https://github.com/medhatdawoud/vuejs-playground) which will be the **Starter Kit**
 2. Instructions about writing code using this starter kit. i.e. where is the student write something like:
  ```
  var name = 'John';
  var counter = 10;
  if (name == 'John'){
    for (i=0; i < counter; i++){
    msg += name;
   }
 }
```    

This concept looks like our daily use of a browser or a plugin that we don't know how does it coded.

The benefits of this approach, it makes easy to introduce new concept, because the student looks at it daily, you just have to pointing towards the concept. In other words, at the end of a course in such way, the student should easily start to learn, HTML, CSS, VueJS  because he/she familiar with these topics during the main course.

**Comment by medhatdawoud** [comment]
Please if this is a video request could you add it to #28 and make it with the same format as other comments so people who are interested in the same idea can vote for you. Thank

**Comment by saidbakr** [comment]
@medhatdawoud No, it is not a video request because it does not has a specific topic. It is only a general idea.

**Comment by medhatdawoud** [comment]
Good idea, thanks for suggesting that, but actually I have a full capacity of planned videos and series, maybe I can consider it later, Thanks again 👍
