### ISSUE TITLE
 في التصميم (سي اس اس٣ و بوتستراب ) اضعف من التطوير (جافاسكريب) 

### ISSUE THREAD

**Issue by Abdofcih** [medhatdawoud/AMA#30]
السلام عليكم 
دلوقت انا شايف اني كويس فرونت اند وبطور من نفسي في البروبلم سولفينج  على موقع
 codewar 
بس في التصميم مش اوي 
(Css3& bootstrap)
اكمل زي منا  في البرمجة ولا اوقف واتقن 
(Css3&bootstrap)

**Comment by medhatdawoud** [comment]
اهلا بيك يا عبدالرحمن

اعتقد دا على حسب انت بتشتغل ايه بالظبط .. يعني لو تعريفك لنفسك انك Frontend Developer يبقى لازم تكون كويس في التصميم زي البرمجة بالظبط اما لو انت JavaScript Developer يبقى مش ضروري اوي انك تكون كويس في التصميم مع اني افضل اي حد شغال في الويب انه يتعلم تصميم

بالتوفيق ليك

**Comment by medhatdawoud** [comment]
Since you didn't respond for that for more than 3 days, I'll take that as you are satisfied with the answer, Goodluck 👍

**Comment by Abdofcih** [comment]
Okay thank you very much for your concern
@medhatdawoud
