### ISSUE TITLE
Meanstack

### ISSUE THREAD

**Issue by shimoaa99** [medhatdawoud/AMA#32]
كنت محتاجه ضروري نود إكسبريس مونجو مين ستاك لان المحتوي العربي التراك دا قليل جدا جدا

**Comment by medhatdawoud** [comment]
اتمنى حضرتك توضحي اكتر .. انتي عاوزة resources ولا عاوزة كورس او فيديوهات ؟

**Comment by shimoaa99** [comment]
حضرتك تعمل كورس كامل وعليه تطبيقات

**Comment by shimoaa99** [comment]
دا كان قصدي بس حضرتك بردو ممكن تدلني عليresouse s جزاكم الله خير انا بدرس
المين ستاك بقالي سنه ومش عارفه اعمل مشروع

**Comment by medhatdawoud** [comment]
ممكن حضرتك تضيفيها في مقترحات الفيديوهات #28  فنقدر نعمل عليها فوت ولو ناس كتير محتاجينها ممكن احطها في الحسبان .. شكرا على اقتراحك
