### ISSUE TITLE
Question about freelancing 

### ISSUE THREAD

**Issue by Mohamed-Abuelatta** [medhatdawoud/AMA#33]
السلام عليكم يا مدحت، 
- انا بشكرك كتير على مجهودك وقناتك على يوتيوب. 
- انا عايز اسال ٥ اسالة عن (الفريلانسنج). كل سؤال هيكون مرفق معاه مثال للتوضيح لكنه طبعا لا يغنى عن الاجابة الاحترافية التى انتظرها منك يا باشمهندس.
- باختصار اذا انا عندى منتج وعايز اسوق له 
١- اسوقله فين (يعنى لو تدينا نبذة عن الفروقات بيت مواقع الفرى لانس وكيفية الاختيار بينها حسب حاجة كل مبرمج)
٢- اسوقله ازاى (يعنى هل انا محتاج اعمل باك لينك زى الناس بتوع SEO ولا موقع الفري لانس هو مسؤل عن كل ما يخص التسويق)
٣- ما هى انواع الفريلانس (يعنى مثلا فى بالقطعة و فى بالمنتج الجاهز ويتم بيعه اكثر من مرة. فهل فى انواع تانية .. عايزين نتكلم عن ده)
٤- ما هى مصطلحات الفريلانسنج التى يجب ان اعرفها لكى ادخل هذا المجال بنجاح (يعنى مثلا هل اشتغل فى اى برنامج بناء على مجرد اتفاق مع العميل ولا بعد ما هو بيحط الفلوس فى حسابى؟ ده بسميه ايه كمصطلح hold مثلا ولا binding معرفش فالحقيقة ؟ وطبعا فى هذه النقطة نريد شرح خطوات الاتفاق مع اى عميل من اول خطوة حتى استلام الفلوس بما يشمل هذا من glossary خاصة بمهنة الفريلانسنج)
٥- اذا عندى فكرة برمجة جديدة محدش عملها قبل كده عايز اطرحها (كيف اعمل لها دراسة جدوى؟ كيف اشهرها؟ كيف اجتذب العملاء؟ مثلا على حد معرفتى العملاء بيحبوا الاوفرز اللى فيها باكدج كمان بيحبوا البروموكود كمان بيحبوا الافيلييت ايه هى الافكار الاحترافية فى هذا الصدد) 

ووالله العظيم كل ده انا لسة لم اعرفه انا فقط اعرف مسميات طشاش كده لكن لسة مش عارفه باحترافية زيك وعايز استفيد منك بجد.

.... اخيرا وليس اخرا ... اسف جدا على الاطالة وانا اعلم ان كل نقطة مما سبق تحتاجلها فيديو لوحدها على ما اعتقد عشان يترد عليها. لذلك يكفينى ان اعرف فقط كيف واين سترد على كل هذه التساؤلات وهل ستكون هنا ام فى فيديو واحد ام عدة فيديوهات. انا ساصبر حتى تجهز الرد على راحتك. بس يا ريت اذا امكن تلفونك للتواصل واتساب فقط للمتابعة لانى عندى اسئلة ومواضيح غاية فى الاهمية وهى مواضيع عملاقة صعب تناولها كلها على github. 

وشكرا جزيلا مقدما ...

**Comment by medhatdawoud** [comment]
هل السؤال دا مختلف عن السؤال التاني ولا نفسه ؟ في اي حال لو فيه اي اضافة اتمنى تكون في كومنت على نفس الايشو حتى لو مش بتاعتك

**Comment by Mohamed-Abuelatta** [comment]
لا هو نفسه يا باشمهندس
