### ISSUE TITLE
what the meaning of props.children

### ISSUE THREAD

**Issue by MostafaDbagh** [medhatdawoud/AMA#34]
what the meaning of props.children and when i can use it if you give us examples 

وبكون ممنونك كتير ومشكور ئلك اذا بتحكيلنا عن advanced guide

**Comment by medhatdawoud** [comment]
I've marked this as a video request because it's way better to reply to you in a video instead of writing .. just stay tuned, and thanks for the great question

**Comment by medhatdawoud** [comment]
Hi Mostafa,

That's a very good question, do you know that React is converting all the JSX into javascript first even the markup, so just to clarify that, the following code:
```jsx
<div>Hello world!</div>;
```
is getting converted to this code:
```js
React.createElement('div', null, `Hello world`);
```
during the rendering phase, so the last parameter in the `createElement` function is always the children object that you might use as well, another example is the following.

Any change included inside the wrapper in translated to `props.children`, if you are creating a wrapper component for example `Alert` component that you would like to send it only the text wrapped inside it, you can use `props.children` as follow:
```jsx
export const Alert = (props) => {
  return (
    <div>
      {props.children}
    </div>
  )
}
``` 
Now when you send anything inside the `Alert` component will be visible indie that div as follow:
```jsx
<Alert>I'm a text to be shown in alert</Alert>
```

That's is, I hope you got it.

Goodluck,
Medhat
