### ISSUE TITLE
تعليق بخصوص فيديو CAT اﻷخير

### ISSUE THREAD

**Issue by saidbakr** [medhatdawoud/AMA#35]
نقطة يجوز إنت قلتها صح لكن ما ركزتش عليها بحيث ممكن تغيب وهي التعلم. المفروض إن المطور بيتعلم حاجات جديدة بغض النظر هيشتغل بيها ولاء وعلى اﻷقل كل سنة المفروض يبقى اتعلم حاجة جديدة.
هنا نتكلم عن تعريف التعلم، وهو موش بالضروري لما تتعلم حاجة إنك تحترفها، وإنها تبقى مجال عملك اﻷساسي، الفكرة بالضبط زي فكرتك مع فيو او مع الريجلولار إكسربيشن. لكن نتفق إن التعلم ما يكونش على حساب احترافك في مجال شغلك اﻷساسي، يكون في وقت الفراغ.

انا غير متفق إنك قدمت الجيت على تعلم فريموورك، الجيت ده في سياق كلامك نقدر نعتبره كريزة تتحط فوق التورتة، ﻷن اللي بيتعلم بيتعلم أساسيات وهو اللي بيتعلم لوحده، فهو موش محتاج انه يشارك كود مع حد ولا يدخل في مجموعة ﻷنه لسة بيتعلم أساسيات. ممكن الجت يبقى مع الفريم وورك من باب انه يتعلمه حتة حتى يعني يعرف منه اللي هو محتاجه في وقتها وبعد كدة لما ربنا يكرمه وينضم لفريق عمل، بكمل النافص فيه في خلال اسبوع على اﻷكثر.

## نقطة تانية
من 10 او 15 سنة كانت الدنيا عبارة عن كلاينت سايد (فرونت إند اﻷايام دي) وسيرفر سايد (باك إند) وزي ما انت قلت كانت بسيطة خالص. لكن استهجانك للي عمله المحاضر بإنه عمل جدول أسس عليه الصفحة، في وقتها كان اللاي آوت المبني على جدول كان حاجة قياسية لا غبار عليها بل كان هو الشيء المفضل ﻷن في الزمن ده كان جحيم التوافق بين المتصفحات لا يمكن احتماله

**Comment by saidbakr** [comment]
معلش نسيت التأكيد
**الفيديو ممتاز للغاية**

**Comment by medhatdawoud** [comment]
> نقطة يجوز إنت قلتها صح لكن ما ركزتش عليها بحيث ممكن تغيب وهي التعلم. المفروض إن المطور بيتعلم حاجات جديدة بغض النظر هيشتغل بيها ولاء وعلى اﻷقل كل سنة المفروض يبقى اتعلم حاجة جديدة.
> هنا نتكلم عن تعريف التعلم، وهو موش بالضروري لما تتعلم حاجة إنك تحترفها، وإنها تبقى مجال عملك اﻷساسي، الفكرة بالضبط زي فكرتك مع فيو او مع الريجلولار إكسربيشن. لكن نتفق إن التعلم ما يكونش على حساب احترافك في مجال شغلك اﻷساسي، يكون في وقت الفراغ.
> 
> انا غير متفق إنك قدمت الجيت على تعلم فريموورك، الجيت ده في سياق كلامك نقدر نعتبره كريزة تتحط فوق التورتة، ﻷن اللي بيتعلم بيتعلم أساسيات وهو اللي بيتعلم لوحده، فهو موش محتاج انه يشارك كود مع حد ولا يدخل في مجموعة ﻷنه لسة بيتعلم أساسيات. ممكن الجت يبقى مع الفريم وورك من باب انه يتعلمه حتة حتى يعني يعرف منه اللي هو محتاجه في وقتها وبعد كدة لما ربنا يكرمه وينضم لفريق عمل، بكمل النافص فيه في خلال اسبوع على اﻷكثر.

شكرا على الفيدباك ولكن انا مازلت مقتنع باللي قولته جدا .. لانه الشخص لما يتعمل git دا هيفتحله مجال في الـ opensource انه يشوف اكواد تعلمه اي حاجة .. تعلم فريبمورك للي فاهم اساسيات كويس ولا حاجة وتخلص في ثواني وممكن يغيرها بعد كام شهر انما علمه بالجيت مش هيتغير وهيعيش معاه طول كاريره

> ## نقطة تانية
> من 10 او 15 سنة كانت الدنيا عبارة عن كلاينت سايد (فرونت إند اﻷايام دي) وسيرفر سايد (باك إند) وزي ما انت قلت كانت بسيطة خالص. لكن استهجانك للي عمله المحاضر بإنه عمل جدول أسس عليه الصفحة، في وقتها كان اللاي آوت المبني على جدول كان حاجة قياسية لا غبار عليها بل كان هو الشيء المفضل ﻷن في الزمن ده كان جحيم التوافق بين المتصفحات لا يمكن احتماله

للاسف برضو مش متفق اوي معاك في دا لانه الكلام دا كان ايام الـ div ماطلع وكان موجودله support في كل البراوزرز كمان .. الفكرة كلها انه كان استسهال مش حاجة لا غبار عليها ولا كان مفضل غير من الناس اللى مايتعرفش cssكويس .. ودا يرجعني لقناعتي انه اي حد بيشتغل في الويب المفروض يكون بيعرف HTML وCSS كويس بدرجات بقى على حسب كم احتكاكه بيهم

اشكرك تاني على تعليقاتك و اتمنى تكون وجهة نظري وصلتلك

**Comment by saidbakr** [comment]
عاوز افكرك فقط بمقولتك الشهيرة:
Done is better than perfect
كلامك رائع ولكنه فيه أجزاء مثالية زيادة عن اللزوم (من وجهة نظري) وموش غلط طبعا. أعتقد إنك لو راجعت تاريخك المهني بدقة غالبا موش هتكون مشيت على الوصفة دي بحذافيرها.
من وجهة نظري، علشان تشارك في مجتمع زي جتهاب لازم يبقى عندك اللي تشارك بيه الاول، الامر بالضبط زي ما اشارك في ريبو صيني عن اﻷدب الصيني وانا ما اعرفش حتى اللغة الصيني
طبعا التركيز على الجافاسكريبت الخام والتمكن فيها أمر حتمي وأساسي اتفق معاك فيها. إنما ما يعتبرش نفسه فرونت إند غير كمان لما يعرف تفاصيل التفاصيل بتاعة
CSS و HTML
في حين إن في وظيفة تانية هي دي مهمتها اﻷساسية أعتقد برضه إنها مبالغة

أما عن النقطة التانية، فدليلي فيها إن كان في وقتها تطبيقات كبيرة جدا ومشهورة كانت معتمدة على 
table layout
زي [phpnuke](https://web.archive.org/web/20010404215915/http://phpnuke.org/)

وتقبل وافر تحياتي وأرجو أن نرى أول فيديوهات القناة الجديدة قريبا.
