### ISSUE TITLE
Semantic HTML

### ISSUE THREAD

**Issue by waleed-maher** [medhatdawoud/AMA#36]
good source for understanding it & best way to practice on it

**Comment by medhatdawoud** [comment]
Hi Waleed,

The best source to learn HTML is the best docs in my opinion on MDN
https://developer.mozilla.org/en-US/docs/Web/HTML

afterwards, the best way to practise is to watch some course and apply what the instructor apply, and in the end, pick one part of a popular site and try to make a similar design like it using HTML and CSS only.

keep me posted with how was your journey.

good luck. Medhat

**Comment by medhatdawoud** [comment]
Since you didn't respond for that for more than 3 days, I'll take that as you are satisfied with the answer, Goodluck 👍
