### ISSUE TITLE
سؤال عن الفريلانسنج

### ISSUE THREAD

**Issue by Mohamed-Abuelatta** [medhatdawoud/AMA#37]
مرحبا باشمهندس،
عفوا سؤالى طويل شوية ومن اكثر من بند ويحتاج فيديو للرد عليه.

١- انواع الفريرلانسنج ايه (على حد علمى اما بالقطعة لكل عميل على حده او بالبروجكت بان يتم عمل منتج متكامل زى ادارة جيم مثلا وطرحه على النت وهو يبيع نفسه اكثر من مرة) هل هناك انواع واساليب اخرى 

٢- انواع مواقع الفريلانس والفروق بينها (هذه مرتبطة باللى قبلها نوعا ما ولكن المقصود هنا من حيث التصنيف بين الاخرين المنافسين، سهولة التعامل، كثرة العملاء، نسبة الربح ونسبة الموقع، ....الخ)

٣- ما هى الخطوات العملية التى يجب معرفتها للدخول فى عالم الفريلانس ؟ يعنى ما هى الخطوات من اول الاتفاق مع العميل الى استلام الفلوس؟ (برجاء توضيح موسوعة المصطلحات الواجب معرفتها لكى اكون مستعد فى هذا المجال) 

٤- ما هى الاسلايب التسويقية الحديثة بما تشمله من مصطلحات لان كثير من المستثمرين الصغار او المبرمجين المتوسطين على دراية بالكود وليس لهم اى علاقة بكور بالبزنس ولذلك يظل المبرمج بما يملكه من امكانات جبارة عبد عند stakeholders للاسف ( اقصد هنا بعض المصطلحات مثل affiliate, promo code, .... etc) مع العلم انى لا اعلم اللى انا كاتبه ده معناه ايه وكل ما اعرفه انه اسلوب لجذب العملاء لتحقيق مبيعات اكثر

٥- اذا انا كمبرمج عندى فكرة برنامج واعدة (خدمى) وحابب اعملها موقع خاص و خطة اسعار والدنيا دى كده كلها زى الشركات العملاقة ... الموضوع ده محتاج انى اتعلم ايه وادرسه ازاى ؟ (عشان تفهم قصدى اليك بعض الامثلة ... مثلا هل محتاج اتعلم seo، هل محتاج اعرف انواع landing pages، هل محتاج اتعلم كيفية برمجة الدفع اونلاين عن طريق الكريديت كارد والباى بال، هل محتاج اعرف اجرائات قانونية معينة، .....الخ) 

اخيرا وليس اخرا، كل اسالتى تتمحور حول عنل استقلالية لنفسى كحر بعيدا عن العمل كموظف فبرجاء الاجابة اذا كانت هتتسجل فيديو يكون هذا المفهوم (الحرية) هو الفكرة الاساسية 

وشكرا جزيلا على قناتك ومجهوداتك لايجاد مجتمع مبرمجين قوى ومتمكن من الادوات الحديثة

**Comment by medhatdawoud** [comment]
اهلا بيك .. اسئلتك كويسة جدا .. هي محتاجة بس حد عنده خبرة اكتر مني شوية في موضوع الفري لانس لاني اشتغلت فيه بس مش كتير .. ممكن اسردلك خبرتي في كومنت او في فيديو ان شاء الله في القريب العاجل .. اسف على انتظارك

**Comment by medhatdawoud** [comment]
اهلا بيك يا محمد 
هاحاول ارد على قدر معرفتي بالموضوع ان شاء الله

> ١- انواع الفريرلانسنج ايه (على حد علمى اما بالقطعة لكل عميل على حده او بالبروجكت بان يتم عمل منتج متكامل زى ادارة جيم مثلا وطرحه على النت وهو يبيع نفسه اكثر من مرة) هل هناك انواع واساليب اخرى

اعتقد دا مش فري لانسينج دا اسمهenterpreneurship او ريادة اعمال و النوع دا من الابليكاشن لو كانت سيرفيس اون لاين بيكون اسمها Saasاو Software as a service غير كدا بقى لو بتعمل زي ثيم او حاجة وتبيعها دا برضو اسمه side project لو مش شغلك الاساسي ولو دا شغلك بس يبقى انت freelancer شغال عند نفسك فاعتقد انه نوع من انواع البيزينيس برضو

> ٢- انواع مواقع الفريلانس والفروق بينها (هذه مرتبطة باللى قبلها نوعا ما ولكن المقصود هنا من حيث التصنيف بين الاخرين المنافسين، سهولة التعامل، كثرة العملاء، نسبة الربح ونسبة الموقع، ....الخ)

ماتعاملتش غير مع واحد بس في بداية كارييري وكان freelance.com وكان لطيف جدا ودا مالوش علاقة بالسؤال اللى قبله

> ٣- ما هى الخطوات العملية التى يجب معرفتها للدخول فى عالم الفريلانس ؟ يعنى ما هى الخطوات من اول الاتفاق مع العميل الى استلام الفلوس؟ (برجاء توضيح موسوعة المصطلحات الواجب معرفتها لكى اكون مستعد فى هذا المجال)

مش هاكذب عليك .. انا تجاربي في الفريلانس قبل ماسيب مصر كانت حوالي ٥ تجارب وكلهم انتهوا نهاية مش احسن حاجة الحقيقة لانه اما لو بتتكلم عن مواقع الفري لانس فدا بيختلف من موقع للتاني بس في الغالب الموقع بياخد الفلوس من العميل وبيديهالك لو العميل كونفيرم انه استلم الشغل حسب الاتفاق

> ٤- ما هى الاسلايب التسويقية الحديثة بما تشمله من مصطلحات لان كثير من المستثمرين الصغار او المبرمجين المتوسطين على دراية بالكود وليس لهم اى علاقة بكور بالبزنس ولذلك يظل المبرمج بما يملكه من امكانات جبارة عبد عند stakeholders للاسف ( اقصد هنا بعض المصطلحات مثل affiliate, promo code, .... etc) مع العلم انى لا اعلم اللى انا كاتبه ده معناه ايه وكل ما اعرفه انه اسلوب لجذب العملاء لتحقيق مبيعات اكثر

ذاكر ماركيتينج .. انا اتعلمت شويه حاجات على مدى شغلي واهم حاجة اتعلمتها بالتجربة هي اني اسوق نفسي قبل ماسوق حاجة انا باعملها.. دي مهارة ولازم تشتغل على نفسك فيها .. مش عارف تحديدا اقولك تعمل ايه بس اتعلم انك تشوف النيد فين وتشتغل عليها كويس 

> ٥- اذا انا كمبرمج عندى فكرة برنامج واعدة (خدمى) وحابب اعملها موقع خاص و خطة اسعار والدنيا دى كده كلها زى الشركات العملاقة ... الموضوع ده محتاج انى اتعلم ايه وادرسه ازاى ؟ (عشان تفهم قصدى اليك بعض الامثلة ... مثلا هل محتاج اتعلم seo، هل محتاج اعرف انواع landing pages، هل محتاج اتعلم كيفية برمجة الدفع اونلاين عن طريق الكريديت كارد والباى بال، هل محتاج اعرف اجرائات قانونية معينة، .....الخ)

اي بيزنيس بيمر بمراحل كتير اهم حاجة انك يكون عندك ناس مستنيين المنتج دا وبعدها انت تقدر تفكر بقى في التكاليف اللى انت بتصرفها عليه وكمان تقدر تحط هامش الربح بتاعك .. بس تاني الاهم اللى تركز عليه انه يكون فين نييد وانت عندك ناس عارفهم محتاجينها ومستعدين يدفعوا فيها وتقدر تعمل معاهم استطلاع وتفهم منهم اكتر وهتقدر تحدد انت الاسعار بتاعتك وتبني سوق

> اخيرا وليس اخرا، كل اسالتى تتمحور حول عنل استقلالية لنفسى كحر بعيدا عن العمل كموظف فبرجاء الاجابة اذا كانت هتتسجل فيديو يكون هذا المفهوم (الحرية) هو الفكرة الاساسية

سعدت بسؤالك .. انت محتاج تكون رائد اعمال مش فري لانسر وان شاء الله هتقدر
