### ISSUE TITLE
Open Edx!

### ISSUE THREAD

**Issue by abdelrahmaan** [medhatdawoud/AMA#39]
Salam bro, i am new in web dev, i have a strong background AlhamdullAaah in problem-solving and Data structure and Algorithms and turned into Data Science and, NLP and Machine Learning from 2 years.
Recently turned into Web for learning it and make integration by ML, so i want to learn Open Edx... i ask for any tracks, ideas, tips and tricks for starting on it and finding anyone for helping me in this journey :).
thanks in advance.

**Comment by medhatdawoud** [comment]
Hi Abdelrahman,

Nice choice, please give me some more details on how could I help you to reach your goal.

Cheers,
Medhat

**Comment by abdelrahmaan** [comment]
Guide for starting OpenEdx, and mentorship.
i tried for reading documentation and didn't get touched it?

**Comment by medhatdawoud** [comment]
I didn't work with OpenEdx before but I worked more or less with most of the techies they are using, so let me know if you need help with React for example.

**Comment by abdelrahmaan** [comment]
okay, what the prerequisite techies can i learning for?

**Comment by medhatdawoud** [comment]
I can help you with react I guess, TBH not sure if you don't know enough what you want how can I help you?

**Comment by medhatdawoud** [comment]
I'll just close this issue and you can re-open it whenever you feel that you need help in some specific thing
