### ISSUE TITLE
How do you structure your react project?

### ISSUE THREAD

**Issue by fdrissi** [medhatdawoud/AMA#4]
How you structure your react project (Components, folders...)

**Comment by medhatdawoud** [comment]
Hi Drissi,

It depends, there is no best way, always what works best for you and your team mates is the best, there are quite a lot of articles talking about that around the internet but you would not find all the same, so just find the best one that support easy readability and maintainability for the whole team and that will be the best structure.

About my structure, I can share the structure of one of the projects I worked with before, it's usually kind the folloing:
```sh
| - components // this is split inside into atomic design
| --- atoms
| --- molecule
| --- organism
| --- pages
| - state // this has everything related to redux and state management
| --- reducers
| --- actions
| --- selectors
...
```
the rest of the project is not special just some.

I hope this helps you. Cheers

**Comment by fdrissi** [comment]
thank you @medhatdawoud, i am reading now about the atomic design.
