### ISSUE TITLE
Invitation for Tunisian JS Community meetup

### ISSUE THREAD

**Issue by houssemAmiri** [medhatdawoud/AMA#40]
Good Morning Mr Medhat Dawoud,
I m Houssem Amiri from Tunisian JS Community. We are a group of JavaScript enthusiasts in Tunisia We discuss js tips, tricks, hacks and frameworks each month in Tunisia. We started at december 2019 and we orgonized 4 meetups. 
I m a follower in your youtube channel from your begunning and really i appricate your video they helped me a lot. Thanks a lot for your effort.
So due to the corona virus We decided to orgonize our April meetup online in zoom. 
We will be very happy if you accept our invitation to make a talk and share with us your experience in js.
if you want to know more about Tunisian js community:
website: https://js-community.tn
facebook: https://facebook.com/TunisianJS/about
linkedin: https://linkedin.com/company/tunisian-js-community/about/?viewAsMember=true
email: contact@js-community.tn
the meetup will be 11 april

**Comment by medhatdawoud** [comment]
Hi Houssem,

It will be an honor to talk in your meetup in Tunisian Community 😍, let's talk offline so I can ask about more details.

Thanks,
Medhat
