### ISSUE TITLE
As Front end developer should be aware about Jenkins and docker ?

### ISSUE THREAD

**Issue by Mmferry** [medhatdawoud/AMA#44]
Because that's happened in the company I'm working in and I get tasks related to that

**Comment by amrsekilly** [comment]
@Mmferry if your company is small (a startup), you might need to do some DevOps work yeah. I did the DevOps at my company for the frontend using Travis. But, I guess Jenkins is more complicated, so it might require a DevOps engineer, that's why I made the decision to use Travis.

**Comment by Mmferry** [comment]
@amrsekilly Thank you Amr for your answer, Actually it's not a startup at all it's one of the biggest tech companies in KSA, there's some tools every developer should know in devOps like docker, Jenkins and kubernetes but as a development perspective as i think devOps care about infrastructure and sure things differ from company to company

**Comment by medhatdawoud** [comment]
Hi @Mmferry,

Thanks @amrsekilly for your answer and it's a valid one for small companies when they want to cut expenses, but the general rule is that as a pure frontend developer you don't have to do that at all, understanding that and helping out if needed but not part of your job description at all, it might depend on the contract you signed and your company but in general and based on my experience as "Frontend Developer" you don't have to write anything related to DevOp.

Good luck.

**Comment by amrsekilly** [comment]
Thanks, Medhat!

In my own experience that's correct. At my previous company, we had a large development team and a DevOps team. 

So I didn't have to do any DevOps work or even know anything about Docker or any CI tools.

But I've been interviewing Egyptian frontend developers lately for my company, and I found out that many of them know about (or do) DevOps work. Maybe it's out of curiosity, IDK!

**Comment by Mmferry** [comment]
Thanks @medhatdawoud  and @amrsekilly I'm really appreciate your answer
