### ISSUE TITLE
How to make HRM for Angular.JS

### ISSUE THREAD

**Issue by Mohamed-Abuelatta** [medhatdawoud/AMA#46]
### Hello Medhat, 

I'm new to this topic. And I'm trying to explore more about it. I saw many videos of yours but I got a lot of terms without applying. Now, it is my turn to ask you (**how to enable HRM for Angular.JS?**). 

_Note: This is just one question if you want to list all questions here please confirm._  
please, expand your answer

**Comment by medhatdawoud** [comment]
That's quite a basic question, by a quick search you might get this as first result
https://medium.com/@beeman/tutorial-enable-hmr-in-angular-cli-apps-1b0d13b80130

not sure if that is helpful
