### ISSUE TITLE
Recommend 5 projects that that make us ready to get hired e.g Askfm

### ISSUE THREAD

**Issue by Abdofcih** [medhatdawoud/AMA#47]
For new developers after learning basics and create some small examples they do not know tow to progress their level how to be advanced developer so can you recommend us **5 projects** that have many features . These projects make us ready to **hired**

**Comment by Mohamed-Abuelatta** [comment]
1- Todo list using react js
2- Book store using angular js
3- Employee management using back end technology such as .net mvc core
4- code bank using both back end and front end, includes recursive function and self relation table and tree view side bar menu 
5- chat app using signalr technology between .Net core and signalr jquery library 
6- emarkting pages with add to cart module and goods view 

... I really wish if I can do all of this 😊

**Comment by medhatdawoud** [comment]
That's quite a good list provided by @Mohamed-Abuelatta , I'm planning to do something like that soon on semicolon academy channel https://www.youtube.com/SemicolonAcademy
