### ISSUE TITLE
YouTube Channel Review

### ISSUE THREAD

**Issue by amrsekilly** [medhatdawoud/AMA#49]
Hello Medhat, 

Your YouTube channel inspired me to start a new YouTube channel last January.

My channel discusses technical frontend stuff and provides career advice about remote work, freelancing, and working in Egypt.

Can you please review some of my content and provide me with your feedback on how to improve the channel? **For example, which topics I should be more focused on, bad things that you noticed on my channel, etc.**

Thanks in advance! 

My channel's link: https://youtube.com/amrsekilly

**Comment by medhatdawoud** [comment]
Hi Amr,

I've checked your channel and it looks good, you have quite good videos, about the topics you should focus on, it's up to your experience and it's obvious that you are working as a Frontend developer, nothing that I notice bad in your channel, just keep creating videos and your video quality will be better and better by time.

Never stop teaching people. good luck.

**Comment by amrsekilly** [comment]
Thank you so much Medhat for your feedback! 🙏🏼
