### ISSUE TITLE
Code design and architecture

### ISSUE THREAD

**Issue by aymangithub** [medhatdawoud/AMA#6]
انا خريج كلية تربية مش متخصص وشغال
Dotnet developer من سنين
وحاليا شغال flutter منذ سنة تقريبا 
وبعطل واقف كتير في تصميم ال 
Code design
And 
Architecture
في بداية كل مشروع
مش عارف امتى وازاي اختار التصميم والهيكلية المناسبة 
TDD
DDD
MVC
MVP
clean architecture
....
تاية شوية ومحتاج اظبط وأتمكن من الموضوع ده بهدف اني اضمن اني عملت احسن هيكلية تساعدني بعدين على التطوير والتيست
شكرا

**Comment by medhatdawoud** [comment]
اهلا يا أيمن .. وسعيد بانك سألت السؤال دا
الحقيقة دا سؤال مهم جدا وكلنا وقعنا في الفخ دا قبل كدا وانا لحد من قريب.. بس بعد شوية وقت بتكتشف انه انت ممكن تتعمل ديزاين ممتاز من البداية وترجع تغيره بعدين لظروف المتطلبات بتاعة المشروع .. لذلك قرار زي دا ماينفعش يكون قطعى اطلاقا ويكون في دماغك من اول ماتدخل على المشروع ... بالعكس انت تاخد وقتك وتفكر كويس جدا المشروع دا ممكن يوصل لفين ومين اللى بيحط الستوريز بتاعته والفيتشرز بتيجي على هيئة ايه و هل فيه رفاهية ان تبدأ بكتابة التيست قبل الفيتشر ولا لا وبناء على كل دا هتقرر هتمشي في اي اتجاه .. الحاجات العامة اللى انا ممكن انصح بيها هي انك ماتعملش
over optimization 
من البداية لانه دا هيخليك مع الاسف تضيع وقت كتير كان ممكن تعمل فيه شغل وتحسنه بعدين (النقطة دي مش في كل الاحوال عشان بعض القرارات لابد تكون بدري جدا) الحاجة التانية هي انك تراعي وانت شغال دايما انه الجزئية دي ممكن تستخدم في مكان تاني سواء في المشروع دا او اي مشروع تاني ولا لا ولو الاجاية بايوة ممكن يبقى تحاول قدر الامكان تخليها 
Isolated and independant
ودي حاجة عامة مش ليها علاقة باركيتيكشر .. لو عاوز تقرأ اكتر في الديزاين باتيرنس دا هيكون مفيد وانصحك تتفرج على مشاريع اوبن سورس كتير ودا هيخليك تتعلم دا بسرعة جدا باذن الله

اتمنى تكون اجابني ساعدتك .. بالتوفيق

**Comment by aymangithub** [comment]
الإجابة طمنتي أني بفكر وماشي في الطريق الصحيح
ونبهتني فعلاً اني اخلي بالي من ال 
over optimization
لأني واحد من الناس بحب اعمل الحاجة كويس جداً 
ولكن زي ما انا فهمت من الاجابة ان ده مش هييجي عمره من أول طلعه للمشروع :)
من ناحية أخرى بحاول أتمرس على ال
Clean Architecture
من الراجل الجميل ده 
https://www.youtube.com/playlist?list=PLB6lc7nQ1n4iYGE_khpXRdJkJEp9WOech

أنا شاكر لإجابتك وأكيد طبعاً ساعدتني

**Comment by medhatdawoud** [comment]
The playlist you shared is so nice for people interested in Flutter
