### ISSUE TITLE
Front-End to Full-Stack development, path way

### ISSUE THREAD

**Issue by Mina-Mishail** [medhatdawoud/AMA#7]
سؤالي: أنا لسة بادء في موضوع ال Front End  و مخطط لدراسة و العمل علي Full stack  و حاليا خلصت ال HTML  و بخلص في CSS  و بعدها مخطط لل (ES5) JS  ثم ES6  

هل هناك أي تقنيات أساسية أو فرعية يمكنني أن أتعلمها بالإضافة إلي ما ذكرت لكي أتمكن من العمل بشكل محترف كا Professional font end & Full stack developer  ؟
و هل في مجال العمل الإحترافي بالشركات ال Multi-national  أو حتي International هناك فريق متخصص في الشركة للـ   UX بالإضافة إلي فريق ال Developers  ولا أنت بتبقي المسؤل عن ال UX design و عن ال developing ؟

ملاحظة : عندي خبرة سابقة في مجال ال systems analysis  و ال DB design و البرمجة بال  C#  ممكن أستخدمها في Full-stack development segment.

هل هناك سن أقصي للبحث عن عمل في مجال ال Full stack  خارج مصر ،و لو عندي أسرة صغيرة هل أقدر ألاقي فرصة عمل  و أسافر و هما معايا  ؟

**Comment by Mina-Mishail** [comment]
Good day @medhatdawoud , I wish you read from you soon.

Many thanks for your advises & support in advanced

**Comment by Mina-Mishail** [comment]
@medhatdawoud , As long as you said these are a GOOD QUESTION for many people, I Hope to hear from you soon in order to have a new info. base to to re-plan my path.

Thanks in advanced.

**Comment by medhatdawoud** [comment]
@Mina-Mishail I'll answer your question later this week, sorry but I'm making something specially for you r question that I'll announce later

**Comment by Mina-Mishail** [comment]
Excuse me @medhatdawoud , Just eager to continue my path by having a professional plan.

Thanks in advanced for your support.

**Comment by medhatdawoud** [comment]
اهلا مينا 

معلش لو كنت اتأخرت في الرد عليك بس كنت مشغول شوية .. وكمان ماكنتش عارف اقرأ الكلام بتاعك بس بعد ما عملت الاكستنشن اللى اتكلمت عنه في الفيديو على اليوتيوب .. قدرت اقرأ واجاوبك

chrome ext: https://chrome.google.com/webstore/detail/rtl-fixer/mkeclhaiiffmeeokkomoameekkpiiecf
video: https://www.youtube.com/watch?v=AH6l4Y27iJ4

> سؤالي: أنا لسة بادء في موضوع ال Front End و مخطط لدراسة و العمل علي Full stack و حاليا خلصت ال HTML و بخلص في CSS و بعدها مخطط لل (ES5) JS ثم ES6

انت ماشي كويس جدا بس ملحوظة انت مش محتاج تأجل ES6 لحد ماتحلص ES5

> هل هناك أي تقنيات أساسية أو فرعية يمكنني أن أتعلمها بالإضافة إلي ما ذكرت لكي أتمكن من العمل بشكل محترف كا Professional font end & Full stack developer ؟

لو على التكنولوجيز فهي كتير جدا ومش بتخلص فانا دايما بانصح انك تلاقي شغل حالا باللي انت عارفه ومع الشغل انت هتعرف اكتر ايه المطلوب تتعلمه .. ماتتعلمش حاجة just in case

> و هل في مجال العمل الإحترافي بالشركات ال Multi-national أو حتي International هناك فريق متخصص في الشركة للـ UX بالإضافة إلي فريق ال Developers ولا أنت بتبقي المسؤل عن ال UX design و عن ال developing ؟

فيه شركات وشركات .. على حسب بس في الغالب بيكون فيه UX designer واللى حابب اضيفه هنا انك انت كـFrontend Developer محتاج يكون عندك خلفية عن الـ User Experience و يكون ليك Input في الموضوع دا بشكل كبير بناء على خبرتك لكن اكيد الافضل يكون فيه UX designer مسئول عن الـ visuals

> ملاحظة : عندي خبرة سابقة في مجال ال systems analysis و ال DB design و البرمجة بال C# ممكن أستخدمها في Full-stack development segment.

دا اكيد وتاني باقولك على حسب الشركة اللى انت هتشتغل فيها .. دا ممكن يكون كمان نقطة قوة ليك لو الشركة محتاجة الخبرات دي

> هل هناك سن أقصي للبحث عن عمل في مجال ال Full stack خارج مصر ،و لو عندي أسرة صغيرة هل أقدر ألاقي فرصة عمل و أسافر و هما معايا ؟

بالتأكيد ينفع ومافيش حد اقصى خالص للسن .. ده رقم 🙂

اتمنى اكون قدرت اجاوبك على أسئلتك وآسف لو كنت اتأخرت عليك
بالتوفيق .. مدحت

**Comment by medhatdawoud** [comment]
I'll close this ticket and if the answer was not enough let's reopen it of add comment to it

**Comment by Mina-Mishail** [comment]
Fist , Thanks considering my question as an important to you.

Even my point to begin a professional path was having a specific basics subjects to advanced to learn , not only just in case subject.

But I took a chance to come back to Tech. business when current employer asked me to develop a website for the company.

Hope to acquire  more science & experience during this project by learning more specific & just in case topics.

Thanks again  @medhatdawoud  for your concise reply.
