### ISSUE TITLE
ماهي افضل طريقة للتعديل على ملفات الفديوهات ؟

### ISSUE THREAD

**Issue by faisalCoding** [medhatdawoud/AMA#9]
هل يوجد طريقة بالجافاسكرب او اي تقنية ويب او حتى موبايل اقدر اتعامل مع ملفات الفديو و اسويلها ابلود ورجعها داونلود مع التعديل؟

**Comment by medhatdawoud** [comment]
please provide more details, I don't understand what you mean

**Comment by medhatdawoud** [comment]
Hi Faisal,

I'll close this ticket since I got no reaction from you for a while, so I'll assume that the question is not that important for you any more, if you have any further questions always write it here as well.

Regards,
Medhat
